name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update gist
        uses: AndyYuan-Oni/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 042351d3b94db524923c64e16812978e
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
